#!/usr/bin/env python3
"""Inventory and audit a repository-stratified C8 v3 code source pool.

Files are read from pinned Git objects (`git cat-file`), never from mutable
working trees. The audit classifies exclusions, reports repository, language,
identifier, exact-duplicate, and SimHash near-duplicate composition, applies
predeclared cap scenarios, and verifies frozen output hashes when configured.
"""

from __future__ import annotations

import argparse
import hashlib
import json
import re
import subprocess
from collections import Counter, defaultdict
from dataclasses import dataclass
from pathlib import Path
from typing import Any


LANGUAGES = {
    ".c": "C",
    ".cc": "C++",
    ".cpp": "C++",
    ".h": "C/C++ header",
    ".hpp": "C++ header",
    ".cs": "C#",
    ".go": "Go",
    ".java": "Java",
    ".js": "JavaScript",
    ".jsx": "JavaScript",
    ".kt": "Kotlin",
    ".kts": "Kotlin",
    ".lua": "Lua",
    ".php": "PHP",
    ".py": "Python",
    ".rb": "Ruby",
    ".rs": "Rust",
    ".scala": "Scala",
    ".sh": "Shell",
    ".sql": "SQL",
    ".swift": "Swift",
    ".ts": "TypeScript",
    ".tsx": "TypeScript",
    ".json": "JSON/config",
    ".jsonc": "JSON/config",
    ".toml": "TOML/config",
    ".yaml": "YAML/config",
    ".yml": "YAML/config",
    ".xml": "XML/config",
}
SPECIAL_FILENAMES = {
    "Dockerfile": "Dockerfile",
    "Makefile": "Makefile",
    "BUILD": "Build",
    "BUILD.bazel": "Build",
    "WORKSPACE": "Build",
}
IDENTIFIER = re.compile(r"[A-Za-z_][A-Za-z0-9_]*")
TOKEN = re.compile(r"[A-Za-z_][A-Za-z0-9_]*|\d+|[^\w\s]", re.UNICODE)
COMMENT_OR_STRING = re.compile(
    r'"""[\s\S]*?"""|\'\'\'[\s\S]*?\'\'\'|/\*[\s\S]*?\*/|//[^\n]*|#[^\n]*|'
    r'"(?:\\.|[^"\\])*"|\'(?:\\.|[^\'\\])*\'|`(?:\\.|[^`\\])*`'
)
GENERATED_MARKERS = (
    "do not edit",
    "auto-generated",
    "autogenerated",
    "generated by",
    "@generated",
)
IDENTIFIER_STOPWORDS = frozenset(
    """
    alignas alignof and as async auto await become bool box break case catch
    char class compl concept const constexpr consteval constinit continue crate
    decltype default defer def delete do double dyn else enum explicit export
    extends extern false final finally float fn for foreach from function go
    goto if impl implements import in inline instanceof int interface internal
    is let lock long loop match mod module move mut namespace native new nil
    noexcept not null nullptr object operator or override package pass private
    protected protocol public raise readonly ref register requires return
    sealed self short signed sizeof static string struct super switch
    synchronized template this throw throws trait transient true try type
    typedef typeid typename uint union unsafe unsigned use using var virtual
    void volatile where while with yield
    """.split()
)


@dataclass
class FileRecord:
    repository: str
    commit: str
    path: str
    language: str
    license_classification: str
    byte_count: int
    sha256: str
    normalized_sha256: str
    simhash64: int
    identifiers: Counter[str]

    def inventory_row(self) -> dict[str, Any]:
        return {
            "repository": self.repository,
            "commit": self.commit,
            "path": self.path,
            "language": self.language,
            "license_classification": self.license_classification,
            "bytes": self.byte_count,
            "sha256": self.sha256,
            "normalized_sha256": self.normalized_sha256,
            "simhash64": f"{self.simhash64:016x}",
        }


def _git(repo: Path, *args: str) -> bytes:
    result = subprocess.run(
        ["git", "-C", str(repo), *args],
        capture_output=True,
        check=True,
    )
    return result.stdout


def resolve_repository(spec_path: Path, repo_spec: dict[str, Any]) -> Path:
    configured = [repo_spec["path"], *repo_spec.get("local_candidates", [])]
    resolved = []
    for value in configured:
        path = Path(value)
        if not path.is_absolute():
            path = (spec_path.parent / path).resolve()
        resolved.append(path)
        if (path / ".git").exists():
            return path
    raise FileNotFoundError(
        f"{repo_spec['id']} is unavailable; checked {', '.join(map(str, resolved))}. "
        "Run fetch_code_pool.py to populate the canonical cache."
    )


def normalized_git_url(url: str) -> str:
    return url.removesuffix("/").removesuffix(".git")


def language_for(path: str) -> str | None:
    name = Path(path).name
    return SPECIAL_FILENAMES.get(name) or LANGUAGES.get(Path(path).suffix.lower())


def path_exclusion(path: str, excluded_components: set[str]) -> str | None:
    components = {part.lower() for part in Path(path).parts}
    matched = sorted(components & excluded_components)
    if matched:
        return f"excluded_path_component:{matched[0]}"
    lower_name = Path(path).name.lower()
    if ".min." in lower_name or lower_name.endswith((".map", ".lock")):
        return "minified_or_lockfile_name"
    return None


def content_exclusion(content: bytes, minified_average_line_bytes: int) -> str | None:
    if b"\x00" in content:
        return "binary_nul"
    prefix = content[:4096].decode("utf-8", errors="ignore").lower()
    if any(marker in prefix for marker in GENERATED_MARKERS):
        return "generated_marker"
    lines = content.splitlines() or [content]
    if len(content) >= 20_000 and len(content) / len(lines) > minified_average_line_bytes:
        return "minified_line_length"
    try:
        content.decode("utf-8")
    except UnicodeDecodeError:
        return "invalid_utf8"
    return None


def normalize_identifier(identifier: str) -> str:
    return re.sub(r"\d+", "#", identifier.lower())


def identifier_counts(text: str) -> Counter[str]:
    # Cross-language lexical approximation. It deliberately removes comments
    # and string literals so English prose and serialized payload keys do not
    # dominate the repeated-identifier diagnostic.
    code_only = COMMENT_OR_STRING.sub(" ", text)
    normalized = (normalize_identifier(item) for item in IDENTIFIER.findall(code_only))
    return Counter(
        item
        for item in normalized
        if len(item) > 1 and item not in IDENTIFIER_STOPWORDS
    )


def normalized_content(text: str) -> str:
    return " ".join(TOKEN.findall(text))


def simhash64(text: str) -> int:
    tokens = TOKEN.findall(text)
    if not tokens:
        return 0
    shingles = ["\0".join(tokens[index : index + 5]) for index in range(max(1, len(tokens) - 4))]
    weights = [0] * 64
    for shingle in shingles:
        value = int.from_bytes(hashlib.blake2b(shingle.encode(), digest_size=8).digest(), "big")
        for bit in range(64):
            weights[bit] += 1 if value & (1 << bit) else -1
    result = 0
    for bit, weight in enumerate(weights):
        if weight >= 0:
            result |= 1 << bit
    return result


def hamming_distance(left: int, right: int) -> int:
    return (left ^ right).bit_count()


def near_duplicate_clusters(records: list[FileRecord], max_distance: int = 3) -> list[list[int]]:
    """Cluster likely near duplicates using four 16-bit SimHash bands."""
    parent = list(range(len(records)))

    def find(index: int) -> int:
        while parent[index] != index:
            parent[index] = parent[parent[index]]
            index = parent[index]
        return index

    def union(left: int, right: int) -> None:
        left_root, right_root = find(left), find(right)
        if left_root != right_root:
            parent[right_root] = left_root

    bands: dict[tuple[int, int], list[int]] = defaultdict(list)
    for index, record in enumerate(records):
        for band in range(4):
            key = (band, (record.simhash64 >> (band * 16)) & 0xFFFF)
            for other in bands[key]:
                if hamming_distance(record.simhash64, records[other].simhash64) <= max_distance:
                    union(index, other)
            bands[key].append(index)

    clusters: dict[int, list[int]] = defaultdict(list)
    for index in range(len(records)):
        clusters[find(index)].append(index)
    return [members for members in clusters.values() if len(members) > 1]


def file_size_summary(records: list[FileRecord]) -> dict[str, Any]:
    sizes = sorted(record.byte_count for record in records)
    if not sizes:
        return {"files": 0, "total_bytes": 0}

    def percentile(fraction: float) -> int:
        return sizes[min(len(sizes) - 1, int(len(sizes) * fraction))]

    return {
        "files": len(sizes),
        "total_bytes": sum(sizes),
        "p50": percentile(0.50),
        "p90": percentile(0.90),
        "p95": percentile(0.95),
        "p99": percentile(0.99),
        "maximum": sizes[-1],
        "files_over_64k": sum(size > 65_536 for size in sizes),
        "files_over_128k": sum(size > 131_072 for size in sizes),
        "files_over_256k": sum(size > 262_144 for size in sizes),
        "bytes_over_128k": sum(size for size in sizes if size > 131_072),
    }


def selection_order(records: list[FileRecord], seed: int) -> list[FileRecord]:
    by_repository: dict[str, list[FileRecord]] = defaultdict(list)
    for record in records:
        by_repository[record.repository].append(record)
    for repository, members in by_repository.items():
        members.sort(
            key=lambda record: hashlib.sha256(
                f"{seed}\0{repository}\0{record.sha256}\0{record.path}".encode()
            ).hexdigest()
        )
    repositories = sorted(by_repository)
    ordered = []
    for rank in range(max((len(members) for members in by_repository.values()), default=0)):
        for repository in repositories:
            members = by_repository[repository]
            if rank < len(members):
                ordered.append(members[rank])
    return ordered


def select_with_caps(
    records: list[FileRecord],
    caps: dict[str, Any],
    target_bytes: int,
    seed: int,
) -> tuple[list[FileRecord], dict[str, int]]:
    max_file = int(caps["maximum_bytes_per_file"])
    max_repository = int(caps["maximum_bytes_per_repository"])
    max_language = int(target_bytes * float(caps["maximum_share_per_language"]))
    max_identifier = int(caps["maximum_occurrences_per_normalized_identifier"])
    max_cluster_files = int(caps["maximum_files_per_near_duplicate_cluster"])

    clusters = near_duplicate_clusters(records)
    cluster_by_key: dict[tuple[str, str], int] = {}
    for cluster_id, cluster in enumerate(clusters):
        for index in cluster:
            record = records[index]
            cluster_by_key[(record.repository, record.path)] = cluster_id

    selected: list[FileRecord] = []
    repo_bytes: Counter[str] = Counter()
    language_bytes: Counter[str] = Counter()
    identifiers: Counter[str] = Counter()
    cluster_files: Counter[int] = Counter()
    rejections: Counter[str] = Counter()
    selected_bytes = 0

    for record in selection_order(records, seed):
        if record.byte_count > max_file:
            rejections["maximum_bytes_per_file"] += 1
            continue
        if selected_bytes + record.byte_count > target_bytes:
            rejections["selection_target_bytes"] += 1
            continue
        if repo_bytes[record.repository] + record.byte_count > max_repository:
            rejections["maximum_bytes_per_repository"] += 1
            continue
        if language_bytes[record.language] + record.byte_count > max_language:
            rejections["maximum_share_per_language"] += 1
            continue
        cluster_id = cluster_by_key.get((record.repository, record.path))
        if cluster_id is not None and cluster_files[cluster_id] >= max_cluster_files:
            rejections["maximum_files_per_near_duplicate_cluster"] += 1
            continue
        if any(
            identifiers[identifier] + count > max_identifier
            for identifier, count in record.identifiers.items()
        ):
            rejections["maximum_occurrences_per_normalized_identifier"] += 1
            continue

        selected.append(record)
        selected_bytes += record.byte_count
        repo_bytes[record.repository] += record.byte_count
        language_bytes[record.language] += record.byte_count
        identifiers.update(record.identifiers)
        if cluster_id is not None:
            cluster_files[cluster_id] += 1

    return selected, dict(sorted(rejections.items()))


def scan_repository(repo_spec: dict[str, Any], exclusions: dict[str, Any]) -> tuple[list[FileRecord], dict[str, Any]]:
    repo = Path(repo_spec["path"]).resolve()
    commit = repo_spec["commit"]
    resolved = _git(repo, "rev-parse", f"{commit}^{{commit}}").decode().strip()
    if resolved != commit:
        raise ValueError(f"{repo_spec['id']} commit must be a full immutable SHA: {commit} resolved to {resolved}")
    configured_url = repo_spec.get("url")
    remote_url = None
    if configured_url:
        try:
            remote_url = _git(repo, "remote", "get-url", "origin").decode().strip()
        except subprocess.CalledProcessError:
            remote_url = None
        if remote_url and normalized_git_url(remote_url) != normalized_git_url(configured_url):
            raise ValueError(
                f"{repo_spec['id']} origin mismatch: expected {configured_url}, got {remote_url}"
            )

    license_path = repo_spec["license_evidence_path"]
    license_content = _git(repo, "cat-file", "blob", f"{commit}:{license_path}")
    license_sha256 = hashlib.sha256(license_content).hexdigest()
    expected_license_sha256 = repo_spec["license_evidence_sha256"]
    if license_sha256 != expected_license_sha256:
        raise ValueError(
            f"{repo_spec['id']} licence evidence mismatch: "
            f"expected {expected_license_sha256}, got {license_sha256}"
        )

    paths = _git(repo, "ls-tree", "-r", "--name-only", commit).decode().splitlines()
    excluded_components = {value.lower() for value in exclusions["path_components"]}
    reasons: Counter[str] = Counter()
    records: list[FileRecord] = []
    code_like_bytes = 0

    for path in paths:
        language = language_for(path)
        if not language:
            continue
        content = _git(repo, "cat-file", "blob", f"{commit}:{path}")
        code_like_bytes += len(content)
        reason = path_exclusion(path, excluded_components)
        if reason is None:
            reason = content_exclusion(content, exclusions["minified_average_line_bytes"])
        if reason:
            reasons[reason] += 1
            continue

        text = content.decode("utf-8")
        identifiers = identifier_counts(text)
        normalized = normalized_content(text)
        records.append(
            FileRecord(
                repository=repo_spec["id"],
                commit=commit,
                path=path,
                language=language,
                license_classification=repo_spec["license_classification"],
                byte_count=len(content),
                sha256=hashlib.sha256(content).hexdigest(),
                normalized_sha256=hashlib.sha256(normalized.encode()).hexdigest(),
                simhash64=simhash64(text),
                identifiers=identifiers,
            )
        )

    return records, {
        "repository": repo_spec["id"],
        "commit": commit,
        "url": configured_url,
        "resolved_path": str(repo),
        "license_classification": repo_spec["license_classification"],
        "license_evidence_path": license_path,
        "license_evidence_sha256": license_sha256,
        "code_like_files_before_filtering": sum(reasons.values()) + len(records),
        "code_like_bytes_before_filtering": code_like_bytes,
        "accepted_files": len(records),
        "accepted_bytes": sum(record.byte_count for record in records),
        "exclusions": dict(sorted(reasons.items())),
    }


def composition(records: list[FileRecord]) -> dict[str, Any]:
    repo_bytes = Counter()
    language_bytes = Counter()
    identifier_occurrences = Counter()
    identifier_bytes = Counter()
    exact: dict[str, list[FileRecord]] = defaultdict(list)
    normalized: dict[str, list[FileRecord]] = defaultdict(list)

    for record in records:
        repo_bytes[record.repository] += record.byte_count
        language_bytes[record.language] += record.byte_count
        exact[record.sha256].append(record)
        normalized[record.normalized_sha256].append(record)
        for identifier, count in record.identifiers.items():
            identifier_occurrences[identifier] += count
            identifier_bytes[identifier] += len(identifier.encode()) * count

    near = near_duplicate_clusters(records)

    def duplicate_rows(groups):
        rows = []
        for digest, members in groups.items():
            if len(members) > 1:
                rows.append(
                    {
                        "digest": digest,
                        "files": len(members),
                        "bytes": sum(member.byte_count for member in members),
                        "members": [f"{member.repository}:{member.path}" for member in members],
                    }
                )
        return sorted(rows, key=lambda row: (-row["bytes"], row["digest"]))

    return {
        "total_files": len(records),
        "total_bytes": sum(record.byte_count for record in records),
        "file_size_bytes": file_size_summary(records),
        "repositories_by_bytes": dict(repo_bytes.most_common()),
        "languages_by_bytes": dict(language_bytes.most_common()),
        "top_identifiers_by_occurrence": identifier_occurrences.most_common(50),
        "top_identifiers_by_contributed_bytes": identifier_bytes.most_common(50),
        "exact_duplicate_clusters": duplicate_rows(exact)[:50],
        "normalized_duplicate_clusters": duplicate_rows(normalized)[:50],
        "near_duplicate_clusters": sorted(
            (
                {
                    "files": len(cluster),
                    "bytes": sum(records[index].byte_count for index in cluster),
                    "members": [f"{records[index].repository}:{records[index].path}" for index in cluster],
                }
                for cluster in near
            ),
            key=lambda row: (-row["bytes"], -row["files"]),
        )[:50],
    }


def materialize_selected_source(
    records: list[FileRecord],
    repositories: dict[str, Path],
    output_path: Path,
) -> dict[str, Any]:
    output_path.parent.mkdir(parents=True, exist_ok=True)
    with output_path.open("w", encoding="utf-8") as handle:
        for record in records:
            content = _git(
                repositories[record.repository],
                "cat-file",
                "blob",
                f"{record.commit}:{record.path}",
            )
            if hashlib.sha256(content).hexdigest() != record.sha256:
                raise AssertionError(f"selected blob changed: {record.repository}:{record.path}")
            handle.write(
                json.dumps(
                    {
                        "source": f"{record.repository}@{record.commit}:{record.path}",
                        "repository": record.repository,
                        "commit": record.commit,
                        "path": record.path,
                        "language": record.language,
                        "license_classification": record.license_classification,
                        "sha256": record.sha256,
                        "text": content.decode("utf-8"),
                    },
                    ensure_ascii=False,
                    separators=(",", ":"),
                )
                + "\n"
            )
    nonempty_records = [record for record in records if record.byte_count > 0]
    unique_records: dict[str, FileRecord] = {}
    for record in nonempty_records:
        unique_records.setdefault(record.sha256, record)
    return {
        "path": str(output_path),
        "sha256": hashlib.sha256(output_path.read_bytes()).hexdigest(),
        "rows": len(records),
        "text_bytes": sum(record.byte_count for record in records),
        "nonempty_rows": len(nonempty_records),
        "empty_rows": len(records) - len(nonempty_records),
        "unique_rows": len(unique_records),
        "unique_text_bytes": sum(record.byte_count for record in unique_records.values()),
        "exact_duplicate_nonempty_rows": len(nonempty_records) - len(unique_records),
    }


def audit(
    spec_path: Path,
    inventory_path: Path,
    report_path: Path,
    selected_source_path: Path | None = None,
    frozen_manifest_path: Path | None = None,
) -> dict[str, Any]:
    spec = json.loads(spec_path.read_text())
    records: list[FileRecord] = []
    repository_reports = []
    resolved_repositories: dict[str, Path] = {}
    for configured_repo in spec["repositories"]:
        repo_spec = dict(configured_repo)
        repo_spec["path"] = str(resolve_repository(spec_path, repo_spec))
        resolved_repositories[repo_spec["id"]] = Path(repo_spec["path"])
        repo_records, repo_report = scan_repository(repo_spec, spec["exclusions"])
        records.extend(repo_records)
        repository_reports.append(repo_report)

    inventory_path.parent.mkdir(parents=True, exist_ok=True)
    with inventory_path.open("w") as handle:
        for record in sorted(records, key=lambda item: (item.repository, item.path)):
            handle.write(json.dumps(record.inventory_row(), separators=(",", ":")) + "\n")

    target_bytes = int(spec.get("selection_target_bytes", 0))
    scenario_results = []
    for scenario in spec.get("cap_scenarios", []):
        selected, rejections = select_with_caps(records, scenario, target_bytes, int(spec.get("seed", 20260725)))
        selected_composition = composition(selected)
        scenario_results.append(
            {
                "id": scenario["id"],
                "selected_files": selected_composition["total_files"],
                "selected_bytes": selected_composition["total_bytes"],
                "target_bytes": target_bytes,
                "target_fill_fraction": (
                    selected_composition["total_bytes"] / target_bytes if target_bytes else None
                ),
                "repositories_by_bytes": selected_composition["repositories_by_bytes"],
                "languages_by_bytes": selected_composition["languages_by_bytes"],
                "rejections": rejections,
            }
        )

    selected_caps = spec.get("selected_caps")
    selected_records: list[FileRecord] = []
    selected_rejections: dict[str, int] = {}
    if selected_caps:
        selected_records, selected_rejections = select_with_caps(
            records,
            selected_caps,
            target_bytes,
            int(spec.get("seed", 20260725)),
        )
        minimum_selected = int(spec.get("minimum_selected_bytes", 0))
        selected_bytes = sum(record.byte_count for record in selected_records)
        if selected_bytes < minimum_selected:
            raise ValueError(
                f"selected pool has {selected_bytes:,} bytes, below frozen minimum "
                f"{minimum_selected:,}"
            )

    selected_source = None
    if selected_records and selected_source_path:
        selected_source = materialize_selected_source(
            selected_records,
            resolved_repositories,
            selected_source_path,
        )

    report = {
        "schema_version": 1,
        "pool_id": spec["pool_id"],
        "status": spec["status"],
        "spec_sha256": hashlib.sha256(spec_path.read_bytes()).hexdigest(),
        "selection_status": (
            "frozen caps selected"
            if selected_caps
            else (
                "diagnostic only; contribution caps remain unfrozen"
                if not spec.get("cap_scenarios")
                else "cap scenarios present; freeze requires an explicit selected scenario"
            )
        ),
        "identifier_extraction": (
            "cross-language lexical approximation; comments and quoted strings removed, "
            "ASCII identifiers lowercased, digit runs normalized to #, one-character "
            "names and pinned cross-language keywords excluded"
        ),
        "repositories": repository_reports,
        "composition_before_caps": composition(records),
        "cap_scenarios": spec.get("cap_scenarios", []),
        "cap_scenario_results": scenario_results,
        "selected_caps": selected_caps,
        "selection_target_bytes": target_bytes,
        "composition_after_selected_caps": (
            composition(selected_records) if selected_caps else None
        ),
        "selected_cap_rejections": selected_rejections,
        "selected_source": selected_source,
        "required_strata": spec.get("required_strata", []),
        "inventory_path": str(inventory_path),
        "inventory_sha256": hashlib.sha256(inventory_path.read_bytes()).hexdigest(),
    }
    report_path.parent.mkdir(parents=True, exist_ok=True)
    report_path.write_text(json.dumps(report, indent=2) + "\n")

    if spec.get("status") == "frozen":
        if not selected_caps or selected_source is None or frozen_manifest_path is None:
            raise ValueError(
                "frozen pool requires selected caps, a selected source output, "
                "and a frozen manifest path"
            )
        expected_outputs = spec["expected_outputs"]
        actual_outputs = {
            "inventory_sha256": report["inventory_sha256"],
            "selected_source_sha256": selected_source["sha256"],
            "selected_rows": selected_source["rows"],
            "selected_text_bytes": selected_source["text_bytes"],
            "selected_nonempty_rows": selected_source["nonempty_rows"],
            "selected_empty_rows": selected_source["empty_rows"],
            "selected_unique_rows": selected_source["unique_rows"],
            "selected_unique_text_bytes": selected_source["unique_text_bytes"],
        }
        if actual_outputs != expected_outputs:
            raise ValueError(
                "frozen output mismatch:\n"
                f"expected={json.dumps(expected_outputs, sort_keys=True)}\n"
                f"actual={json.dumps(actual_outputs, sort_keys=True)}"
            )
        before = report["composition_before_caps"]
        after = report["composition_after_selected_caps"]
        manifest = {
            "schema_version": 1,
            "pool_id": spec["pool_id"],
            "status": "frozen",
            "spec_path": spec_path.name,
            "spec_sha256": report["spec_sha256"],
            "seed": int(spec["seed"]),
            "selection": (
                "round-robin by repository; SHA-256(seed, repository, blob SHA, path) "
                "within repository; whole files only"
            ),
            "repositories": [
                {
                    key: repository[key]
                    for key in (
                        "id",
                        "url",
                        "commit",
                        "license_classification",
                        "license_evidence_path",
                        "license_evidence_sha256",
                    )
                }
                for repository in spec["repositories"]
            ],
            "inventory_sha256": report["inventory_sha256"],
            "reproducibility": {
                "status": "verified by two independent materializations",
                "expected_outputs": expected_outputs,
            },
            "selected_source": {
                **selected_source,
                "path": selected_source_path.name,
            },
            "caps": selected_caps,
            "cap_selection_rationale": spec["cap_selection_rationale"],
            "before_caps": {
                "files": before["total_files"],
                "bytes": before["total_bytes"],
                "repositories_by_bytes": before["repositories_by_bytes"],
                "languages_by_bytes": before["languages_by_bytes"],
                "file_size_bytes": before["file_size_bytes"],
                "top_identifiers_by_occurrence": before["top_identifiers_by_occurrence"][:20],
            },
            "after_caps": {
                "files": after["total_files"],
                "bytes": after["total_bytes"],
                "repositories_by_bytes": after["repositories_by_bytes"],
                "languages_by_bytes": after["languages_by_bytes"],
                "file_size_bytes": after["file_size_bytes"],
                "top_identifiers_by_occurrence": after["top_identifiers_by_occurrence"][:20],
                "exact_duplicate_clusters": len(after["exact_duplicate_clusters"]),
                "normalized_duplicate_clusters": len(after["normalized_duplicate_clusters"]),
                "near_duplicate_clusters": len(after["near_duplicate_clusters"]),
            },
            "rejections": selected_rejections,
        }
        frozen_manifest_path.parent.mkdir(parents=True, exist_ok=True)
        frozen_manifest_path.write_text(json.dumps(manifest, indent=2) + "\n")
    return report


def main() -> None:
    here = Path(__file__).resolve().parent
    parser = argparse.ArgumentParser()
    parser.add_argument("--spec", type=Path, default=here / "code_pool_spec.json")
    parser.add_argument("--inventory", type=Path, default=here / "code_pool_inventory.jsonl")
    parser.add_argument("--report", type=Path, default=here / "code_pool_audit.json")
    parser.add_argument(
        "--selected-source",
        type=Path,
        default=here / "code_pool_selected.jsonl",
    )
    parser.add_argument(
        "--frozen-manifest",
        type=Path,
        default=here / "code_pool_frozen_manifest.json",
    )
    args = parser.parse_args()
    print(
        json.dumps(
            audit(
                args.spec.resolve(),
                args.inventory.resolve(),
                args.report.resolve(),
                args.selected_source.resolve(),
                args.frozen_manifest.resolve(),
            ),
            indent=2,
        )
    )


if __name__ == "__main__":
    main()
