#!/usr/bin/env python3
"""Inventory and audit a repository-stratified C8 v3 code source pool.

Files are read from pinned Git objects (`git cat-file`), never from mutable
working trees. The first pass is diagnostic: it classifies exclusions and
reports repository, language, identifier, exact-duplicate, and SimHash
near-duplicate composition before any contribution caps are frozen.
"""

from __future__ import annotations

import argparse
import hashlib
import json
import re
import subprocess
from collections import Counter, defaultdict
from dataclasses import dataclass
from pathlib import Path
from typing import Any


LANGUAGES = {
    ".c": "C",
    ".cc": "C++",
    ".cpp": "C++",
    ".h": "C/C++ header",
    ".hpp": "C++ header",
    ".cs": "C#",
    ".go": "Go",
    ".java": "Java",
    ".js": "JavaScript",
    ".jsx": "JavaScript",
    ".kt": "Kotlin",
    ".kts": "Kotlin",
    ".lua": "Lua",
    ".php": "PHP",
    ".py": "Python",
    ".rb": "Ruby",
    ".rs": "Rust",
    ".scala": "Scala",
    ".sh": "Shell",
    ".sql": "SQL",
    ".swift": "Swift",
    ".ts": "TypeScript",
    ".tsx": "TypeScript",
    ".json": "JSON/config",
    ".jsonc": "JSON/config",
    ".toml": "TOML/config",
    ".yaml": "YAML/config",
    ".yml": "YAML/config",
    ".xml": "XML/config",
}
SPECIAL_FILENAMES = {
    "Dockerfile": "Dockerfile",
    "Makefile": "Makefile",
    "BUILD": "Build",
    "BUILD.bazel": "Build",
    "WORKSPACE": "Build",
}
IDENTIFIER = re.compile(r"[A-Za-z_][A-Za-z0-9_]*")
TOKEN = re.compile(r"[A-Za-z_][A-Za-z0-9_]*|\d+|[^\w\s]", re.UNICODE)
COMMENT_OR_STRING = re.compile(
    r'"""[\s\S]*?"""|\'\'\'[\s\S]*?\'\'\'|/\*[\s\S]*?\*/|//[^\n]*|#[^\n]*|'
    r'"(?:\\.|[^"\\])*"|\'(?:\\.|[^\'\\])*\'|`(?:\\.|[^`\\])*`'
)
GENERATED_MARKERS = (
    "do not edit",
    "auto-generated",
    "autogenerated",
    "generated by",
    "@generated",
)


@dataclass
class FileRecord:
    repository: str
    commit: str
    path: str
    language: str
    license_classification: str
    byte_count: int
    sha256: str
    normalized_sha256: str
    simhash64: int
    identifiers: Counter[str]

    def inventory_row(self) -> dict[str, Any]:
        return {
            "repository": self.repository,
            "commit": self.commit,
            "path": self.path,
            "language": self.language,
            "license_classification": self.license_classification,
            "bytes": self.byte_count,
            "sha256": self.sha256,
            "normalized_sha256": self.normalized_sha256,
            "simhash64": f"{self.simhash64:016x}",
        }


def _git(repo: Path, *args: str) -> bytes:
    result = subprocess.run(
        ["git", "-C", str(repo), *args],
        capture_output=True,
        check=True,
    )
    return result.stdout


def language_for(path: str) -> str | None:
    name = Path(path).name
    return SPECIAL_FILENAMES.get(name) or LANGUAGES.get(Path(path).suffix.lower())


def path_exclusion(path: str, excluded_components: set[str]) -> str | None:
    components = {part.lower() for part in Path(path).parts}
    matched = sorted(components & excluded_components)
    if matched:
        return f"excluded_path_component:{matched[0]}"
    lower_name = Path(path).name.lower()
    if ".min." in lower_name or lower_name.endswith((".map", ".lock")):
        return "minified_or_lockfile_name"
    return None


def content_exclusion(content: bytes, minified_average_line_bytes: int) -> str | None:
    if b"\x00" in content:
        return "binary_nul"
    prefix = content[:4096].decode("utf-8", errors="ignore").lower()
    if any(marker in prefix for marker in GENERATED_MARKERS):
        return "generated_marker"
    lines = content.splitlines() or [content]
    if len(content) >= 20_000 and len(content) / len(lines) > minified_average_line_bytes:
        return "minified_line_length"
    try:
        content.decode("utf-8")
    except UnicodeDecodeError:
        return "invalid_utf8"
    return None


def normalize_identifier(identifier: str) -> str:
    return re.sub(r"\d+", "#", identifier.lower())


def identifier_counts(text: str) -> Counter[str]:
    # Cross-language lexical approximation. It deliberately removes comments
    # and string literals so English prose and serialized payload keys do not
    # dominate the repeated-identifier diagnostic.
    code_only = COMMENT_OR_STRING.sub(" ", text)
    return Counter(normalize_identifier(item) for item in IDENTIFIER.findall(code_only))


def normalized_content(text: str) -> str:
    return " ".join(TOKEN.findall(text))


def simhash64(text: str) -> int:
    tokens = TOKEN.findall(text)
    if not tokens:
        return 0
    shingles = ["\0".join(tokens[index : index + 5]) for index in range(max(1, len(tokens) - 4))]
    weights = [0] * 64
    for shingle in shingles:
        value = int.from_bytes(hashlib.blake2b(shingle.encode(), digest_size=8).digest(), "big")
        for bit in range(64):
            weights[bit] += 1 if value & (1 << bit) else -1
    result = 0
    for bit, weight in enumerate(weights):
        if weight >= 0:
            result |= 1 << bit
    return result


def hamming_distance(left: int, right: int) -> int:
    return (left ^ right).bit_count()


def near_duplicate_clusters(records: list[FileRecord], max_distance: int = 3) -> list[list[int]]:
    """Cluster likely near duplicates using four 16-bit SimHash bands."""
    parent = list(range(len(records)))

    def find(index: int) -> int:
        while parent[index] != index:
            parent[index] = parent[parent[index]]
            index = parent[index]
        return index

    def union(left: int, right: int) -> None:
        left_root, right_root = find(left), find(right)
        if left_root != right_root:
            parent[right_root] = left_root

    bands: dict[tuple[int, int], list[int]] = defaultdict(list)
    for index, record in enumerate(records):
        for band in range(4):
            key = (band, (record.simhash64 >> (band * 16)) & 0xFFFF)
            for other in bands[key]:
                if hamming_distance(record.simhash64, records[other].simhash64) <= max_distance:
                    union(index, other)
            bands[key].append(index)

    clusters: dict[int, list[int]] = defaultdict(list)
    for index in range(len(records)):
        clusters[find(index)].append(index)
    return [members for members in clusters.values() if len(members) > 1]


def scan_repository(repo_spec: dict[str, Any], exclusions: dict[str, Any]) -> tuple[list[FileRecord], dict[str, Any]]:
    repo = Path(repo_spec["path"]).resolve()
    commit = repo_spec["commit"]
    resolved = _git(repo, "rev-parse", f"{commit}^{{commit}}").decode().strip()
    if resolved != commit:
        raise ValueError(f"{repo_spec['id']} commit must be a full immutable SHA: {commit} resolved to {resolved}")

    paths = _git(repo, "ls-tree", "-r", "--name-only", commit).decode().splitlines()
    excluded_components = {value.lower() for value in exclusions["path_components"]}
    reasons: Counter[str] = Counter()
    records: list[FileRecord] = []
    code_like_bytes = 0

    for path in paths:
        language = language_for(path)
        if not language:
            continue
        content = _git(repo, "cat-file", "blob", f"{commit}:{path}")
        code_like_bytes += len(content)
        reason = path_exclusion(path, excluded_components)
        if reason is None:
            reason = content_exclusion(content, exclusions["minified_average_line_bytes"])
        if reason:
            reasons[reason] += 1
            continue

        text = content.decode("utf-8")
        identifiers = identifier_counts(text)
        normalized = normalized_content(text)
        records.append(
            FileRecord(
                repository=repo_spec["id"],
                commit=commit,
                path=path,
                language=language,
                license_classification=repo_spec["license_classification"],
                byte_count=len(content),
                sha256=hashlib.sha256(content).hexdigest(),
                normalized_sha256=hashlib.sha256(normalized.encode()).hexdigest(),
                simhash64=simhash64(text),
                identifiers=identifiers,
            )
        )

    return records, {
        "repository": repo_spec["id"],
        "commit": commit,
        "license_classification": repo_spec["license_classification"],
        "code_like_files_before_filtering": sum(reasons.values()) + len(records),
        "code_like_bytes_before_filtering": code_like_bytes,
        "accepted_files": len(records),
        "accepted_bytes": sum(record.byte_count for record in records),
        "exclusions": dict(sorted(reasons.items())),
    }


def composition(records: list[FileRecord]) -> dict[str, Any]:
    repo_bytes = Counter()
    language_bytes = Counter()
    identifier_occurrences = Counter()
    identifier_bytes = Counter()
    exact: dict[str, list[FileRecord]] = defaultdict(list)
    normalized: dict[str, list[FileRecord]] = defaultdict(list)

    for record in records:
        repo_bytes[record.repository] += record.byte_count
        language_bytes[record.language] += record.byte_count
        exact[record.sha256].append(record)
        normalized[record.normalized_sha256].append(record)
        for identifier, count in record.identifiers.items():
            identifier_occurrences[identifier] += count
            identifier_bytes[identifier] += len(identifier.encode()) * count

    near = near_duplicate_clusters(records)

    def duplicate_rows(groups):
        rows = []
        for digest, members in groups.items():
            if len(members) > 1:
                rows.append(
                    {
                        "digest": digest,
                        "files": len(members),
                        "bytes": sum(member.byte_count for member in members),
                        "members": [f"{member.repository}:{member.path}" for member in members],
                    }
                )
        return sorted(rows, key=lambda row: (-row["bytes"], row["digest"]))

    return {
        "total_files": len(records),
        "total_bytes": sum(record.byte_count for record in records),
        "repositories_by_bytes": dict(repo_bytes.most_common()),
        "languages_by_bytes": dict(language_bytes.most_common()),
        "top_identifiers_by_occurrence": identifier_occurrences.most_common(50),
        "top_identifiers_by_contributed_bytes": identifier_bytes.most_common(50),
        "exact_duplicate_clusters": duplicate_rows(exact)[:50],
        "normalized_duplicate_clusters": duplicate_rows(normalized)[:50],
        "near_duplicate_clusters": sorted(
            (
                {
                    "files": len(cluster),
                    "bytes": sum(records[index].byte_count for index in cluster),
                    "members": [f"{records[index].repository}:{records[index].path}" for index in cluster],
                }
                for cluster in near
            ),
            key=lambda row: (-row["bytes"], -row["files"]),
        )[:50],
    }


def audit(spec_path: Path, inventory_path: Path, report_path: Path) -> dict[str, Any]:
    spec = json.loads(spec_path.read_text())
    records: list[FileRecord] = []
    repository_reports = []
    for configured_repo in spec["repositories"]:
        repo_spec = dict(configured_repo)
        configured_path = Path(repo_spec["path"])
        if not configured_path.is_absolute():
            repo_spec["path"] = str((spec_path.parent / configured_path).resolve())
        repo_records, repo_report = scan_repository(repo_spec, spec["exclusions"])
        records.extend(repo_records)
        repository_reports.append(repo_report)

    inventory_path.parent.mkdir(parents=True, exist_ok=True)
    with inventory_path.open("w") as handle:
        for record in sorted(records, key=lambda item: (item.repository, item.path)):
            handle.write(json.dumps(record.inventory_row(), separators=(",", ":")) + "\n")

    report = {
        "schema_version": 1,
        "pool_id": spec["pool_id"],
        "status": spec["status"],
        "spec_sha256": hashlib.sha256(spec_path.read_bytes()).hexdigest(),
        "selection_status": (
            "diagnostic only; contribution caps remain unfrozen"
            if not spec.get("cap_scenarios")
            else "cap scenarios present; freeze requires an explicit selected scenario"
        ),
        "identifier_extraction": (
            "cross-language lexical approximation; comments and quoted strings removed, "
            "ASCII identifiers lowercased, digit runs normalized to #"
        ),
        "repositories": repository_reports,
        "composition_before_caps": composition(records),
        "cap_scenarios": spec.get("cap_scenarios", []),
        "required_strata": spec.get("required_strata", []),
        "inventory_path": str(inventory_path),
        "inventory_sha256": hashlib.sha256(inventory_path.read_bytes()).hexdigest(),
    }
    report_path.parent.mkdir(parents=True, exist_ok=True)
    report_path.write_text(json.dumps(report, indent=2) + "\n")
    return report


def main() -> None:
    here = Path(__file__).resolve().parent
    parser = argparse.ArgumentParser()
    parser.add_argument("--spec", type=Path, default=here / "code_pool_spec.json")
    parser.add_argument("--inventory", type=Path, default=here / "code_pool_inventory.jsonl")
    parser.add_argument("--report", type=Path, default=here / "code_pool_audit.json")
    args = parser.parse_args()
    print(json.dumps(audit(args.spec.resolve(), args.inventory.resolve(), args.report.resolve()), indent=2))


if __name__ == "__main__":
    main()
