#!/usr/bin/env python3

import json
import hashlib
import subprocess
import tempfile
import unittest
from pathlib import Path

from v12.corpus.audit_code_pool import (
    audit,
    content_exclusion,
    hamming_distance,
    identifier_counts,
    language_for,
    normalize_identifier,
    select_with_caps,
    FileRecord,
)


class CodePoolAuditTests(unittest.TestCase):
    def test_checked_in_freeze_manifest_matches_spec(self):
        here = Path(__file__).resolve().parent
        spec_path = here / "code_pool_spec.json"
        manifest = json.loads((here / "code_pool_frozen_manifest.json").read_text())
        spec = json.loads(spec_path.read_text())

        self.assertEqual(manifest["status"], "frozen")
        self.assertEqual(
            manifest["spec_sha256"],
            hashlib.sha256(spec_path.read_bytes()).hexdigest(),
        )
        self.assertEqual(spec["selected_caps"]["scenario_id"], "balanced")
        self.assertEqual(
            manifest["reproducibility"]["expected_outputs"],
            spec["expected_outputs"],
        )
        self.assertGreaterEqual(
            manifest["selected_source"]["unique_text_bytes"],
            spec["minimum_selected_bytes"],
        )
        self.assertEqual(len(manifest["repositories"]), 7)
        self.assertTrue(all(len(repository["commit"]) == 40 for repository in manifest["repositories"]))
        c8_spec = json.loads((here / "c8_v3_spec.json").read_text())
        self.assertEqual(
            c8_spec["domains"]["code"]["sources"][0]["sha256"],
            manifest["selected_source"]["sha256"],
        )

        selected_source = here / manifest["selected_source"]["path"]
        if selected_source.exists():
            self.assertEqual(
                hashlib.sha256(selected_source.read_bytes()).hexdigest(),
                manifest["selected_source"]["sha256"],
            )

    def test_classification_and_normalization(self):
        self.assertEqual(language_for("src/main.rs"), "Rust")
        self.assertEqual(language_for("Dockerfile"), "Dockerfile")
        self.assertIsNone(language_for("README.md"))
        self.assertEqual(normalize_identifier("User123ID"), "user#id")
        self.assertEqual(identifier_counts('real_id = "fake_id" // comment_name'), {"real_id": 1})
        self.assertEqual(identifier_counts("const x = named_value; return named_value;"), {"named_value": 2})
        self.assertEqual(hamming_distance(0b1010, 0b0011), 2)

    def test_content_exclusions(self):
        self.assertEqual(content_exclusion(b"// generated by tool\nx", 500), "generated_marker")
        self.assertEqual(content_exclusion(b"a\x00b", 500), "binary_nul")
        self.assertIsNone(content_exclusion(b"fn main() {}\n", 500))

    def test_reads_pinned_git_objects_not_worktree(self):
        with tempfile.TemporaryDirectory() as tmp:
            repo = Path(tmp) / "repo"
            repo.mkdir()
            subprocess.run(["git", "init", "-q", str(repo)], check=True)
            (repo / "main.py").write_text("def committed_name():\n    return 1\n")
            (repo / "generated.js").write_text("// DO NOT EDIT; generated by fixture\nconst x=1;\n")
            license_text = "fixture licence\n"
            (repo / "LICENSE").write_text(license_text)
            subprocess.run(["git", "-C", str(repo), "add", "."], check=True)
            subprocess.run(
                [
                    "git",
                    "-C",
                    str(repo),
                    "-c",
                    "user.name=Fixture",
                    "-c",
                    "user.email=fixture@example.invalid",
                    "commit",
                    "-qm",
                    "fixture",
                ],
                check=True,
            )
            commit = subprocess.check_output(["git", "-C", str(repo), "rev-parse", "HEAD"], text=True).strip()
            # Mutate the working tree after the pin; the audit must still read
            # committed_name from the Git object.
            (repo / "main.py").write_text("def mutable_worktree_name():\n    return 2\n")

            spec = {
                "schema_version": 1,
                "pool_id": "fixture",
                "status": "draft-diagnostic",
                "repositories": [
                    {
                        "id": "fixture",
                        "path": str(repo),
                        "commit": commit,
                        "license_classification": "test-only",
                        "license_evidence_path": "LICENSE",
                        "license_evidence_sha256": hashlib.sha256(
                            license_text.encode()
                        ).hexdigest(),
                    }
                ],
                "exclusions": {"path_components": ["vendor"], "minified_average_line_bytes": 500},
                "required_strata": [],
                "cap_scenarios": [],
            }
            spec_path = Path(tmp) / "spec.json"
            inventory = Path(tmp) / "inventory.jsonl"
            report_path = Path(tmp) / "report.json"
            spec_path.write_text(json.dumps(spec))
            report = audit(spec_path, inventory, report_path)

            self.assertEqual(report["composition_before_caps"]["total_files"], 1)
            self.assertEqual(report["repositories"][0]["exclusions"], {"generated_marker": 1})
            identifiers = dict(report["composition_before_caps"]["top_identifiers_by_occurrence"])
            self.assertIn("committed_name", identifiers)
            self.assertNotIn("mutable_worktree_name", identifiers)

    def test_cap_selection_is_deterministic_and_enforced(self):
        def record(repository, path, language, byte_count, identifiers):
            return FileRecord(
                repository=repository,
                commit="a" * 40,
                path=path,
                language=language,
                license_classification="test",
                byte_count=byte_count,
                sha256=hashlib.sha256(path.encode()).hexdigest(),
                normalized_sha256=hashlib.sha256((path + "-normalized").encode()).hexdigest(),
                simhash64=int.from_bytes(hashlib.blake2b(path.encode(), digest_size=8).digest(), "big"),
                identifiers=identifiers,
            )

        records = [
            record("a", "one.py", "Python", 40, {"shared_name": 2}),
            record("a", "large.py", "Python", 101, {}),
            record("b", "two.rs", "Rust", 40, {"shared_name": 2}),
            record("b", "three.rs", "Rust", 40, {"other_name": 1}),
        ]
        caps = {
            "maximum_bytes_per_file": 100,
            "maximum_bytes_per_repository": 80,
            "maximum_share_per_language": 0.5,
            "maximum_occurrences_per_normalized_identifier": 3,
            "maximum_files_per_near_duplicate_cluster": 2,
        }
        first, first_rejections = select_with_caps(records, caps, 160, 7)
        second, second_rejections = select_with_caps(records, caps, 160, 7)
        self.assertEqual([(item.repository, item.path) for item in first], [(item.repository, item.path) for item in second])
        self.assertEqual(first_rejections, second_rejections)
        self.assertLessEqual(sum(item.byte_count for item in first), 160)
        self.assertNotIn("large.py", {item.path for item in first})


if __name__ == "__main__":
    unittest.main()
