#!/usr/bin/env python3

import json
import subprocess
import tempfile
import unittest
from pathlib import Path

from v12.corpus.audit_code_pool import (
    audit,
    content_exclusion,
    hamming_distance,
    identifier_counts,
    language_for,
    normalize_identifier,
)


class CodePoolAuditTests(unittest.TestCase):
    def test_classification_and_normalization(self):
        self.assertEqual(language_for("src/main.rs"), "Rust")
        self.assertEqual(language_for("Dockerfile"), "Dockerfile")
        self.assertIsNone(language_for("README.md"))
        self.assertEqual(normalize_identifier("User123ID"), "user#id")
        self.assertEqual(identifier_counts('real_id = "fake_id" // comment_name'), {"real_id": 1})
        self.assertEqual(hamming_distance(0b1010, 0b0011), 2)

    def test_content_exclusions(self):
        self.assertEqual(content_exclusion(b"// generated by tool\nx", 500), "generated_marker")
        self.assertEqual(content_exclusion(b"a\x00b", 500), "binary_nul")
        self.assertIsNone(content_exclusion(b"fn main() {}\n", 500))

    def test_reads_pinned_git_objects_not_worktree(self):
        with tempfile.TemporaryDirectory() as tmp:
            repo = Path(tmp) / "repo"
            repo.mkdir()
            subprocess.run(["git", "init", "-q", str(repo)], check=True)
            (repo / "main.py").write_text("def committed_name():\n    return 1\n")
            (repo / "generated.js").write_text("// DO NOT EDIT; generated by fixture\nconst x=1;\n")
            subprocess.run(["git", "-C", str(repo), "add", "."], check=True)
            subprocess.run(
                [
                    "git",
                    "-C",
                    str(repo),
                    "-c",
                    "user.name=Fixture",
                    "-c",
                    "user.email=fixture@example.invalid",
                    "commit",
                    "-qm",
                    "fixture",
                ],
                check=True,
            )
            commit = subprocess.check_output(["git", "-C", str(repo), "rev-parse", "HEAD"], text=True).strip()
            # Mutate the working tree after the pin; the audit must still read
            # committed_name from the Git object.
            (repo / "main.py").write_text("def mutable_worktree_name():\n    return 2\n")

            spec = {
                "schema_version": 1,
                "pool_id": "fixture",
                "status": "draft-diagnostic",
                "repositories": [
                    {
                        "id": "fixture",
                        "path": str(repo),
                        "commit": commit,
                        "license_classification": "test-only",
                    }
                ],
                "exclusions": {"path_components": ["vendor"], "minified_average_line_bytes": 500},
                "required_strata": [],
                "cap_scenarios": [],
            }
            spec_path = Path(tmp) / "spec.json"
            inventory = Path(tmp) / "inventory.jsonl"
            report_path = Path(tmp) / "report.json"
            spec_path.write_text(json.dumps(spec))
            report = audit(spec_path, inventory, report_path)

            self.assertEqual(report["composition_before_caps"]["total_files"], 1)
            self.assertEqual(report["repositories"][0]["exclusions"], {"generated_marker": 1})
            identifiers = dict(report["composition_before_caps"]["top_identifiers_by_occurrence"])
            self.assertIn("committed_name", identifiers)
            self.assertNotIn("mutable_worktree_name", identifiers)


if __name__ == "__main__":
    unittest.main()
